config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, skip: :registrations
  devise_for :staffs, skip: :registrations

  resources :clients, only: [:index, :create] do
    post :check_valid, on: :collection
  end
  
  resources :staffs, only: :index do
    get :me, on: :collection
  end

  get :asset_path, to: 'application#asset_path'
  root to: 'application#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  include Authable

  validates :fullname, presence: true, length: { minimum: 5 }
  validates :phone, uniqueness: true, format: { with: /\A\d+\z/, message: 'must contain digits only' }
end

app/models/concerns/authable.rb
module Authable
  extend ActiveSupport::Concern

  included do
    devise :database_authenticatable, :recoverable, :rememberable, :validatable
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  include Authable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  
  def index; end

  def asset_path
    render json: view_context.image_path(params[:filename])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  layout 'clients'

  before_action :check_staff, only: :create
  before_action :new_client, only: [:create, :check_valid]

  def index
    respond_to do |format|
      format.html
      format.json { render json: Client.all }
    end
  end

  def create
    if @client.save
      render json: @client
    else
      render json: { errors: @client.errors.full_messages }, status: :bad_request
    end
  end

  def check_valid
    if @client.valid?
      head 200
    else
      render json: { errors: @client.errors }, status: :bad_request
    end
  end

  private

  def client_params
    params.require(:client).permit(:fullname, :phone, :email)
  end

  def check_staff
    render json: { error: 'Not authorized' }, status: 401 unless current_staff
  end

  def new_client
    @client = Client.new(client_params)
    random_password = SecureRandom.hex(10)

    @client.password = random_password
    @client.password_confirmation = random_password
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  layout 'staffs'

  def index; end

  def me
    if current_staff
      render json: current_staff
    else
      render json: { message: 'No user logged in' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<div>
    <%= link_to 'Clients', clients_path %>
     |
    <%= link_to 'Staffs', staffs_path %>
</div>

<div>
    <%= link_to 'Log in as Client', new_client_session_path %>
     |
    <%= link_to 'Log in as Staff', new_staff_session_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VueProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/clients.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VueProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'clients' %>
  </head>

  <body>
    <div id="app">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/staffs.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VueProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'staffs' %>
  </head>

  <body>
    <div id="app">
      <%= yield %>
    </div>
  </body>
</html>